### ISSUE TITLE
Trocar ícone de hambúrguer por usuário(a) no menu

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/dez#21]
Estava observando o menu que se abre ao clicar/tocar no ícone de hambúrguer, e notei que, com algumas mudanças, daria para deixar todos ali relacionados a opções do(a) usuário(a).

Acho que haveria um ganho em percepção bem importante. Trocaríamos algo genérico (hambúrguer) por um ícone que comunica algo (uma silhueta de pessoa, um usuário, que diz “clique aqui para ver itens que dizem respeito a você”).

Como consequência, talvez mais pessoas descobrissem o cadastro, o Órbita e outras partes interativas do **Manual**.

Sugestão de ícone: https://www.svgrepo.com/svg/507440/user

![user-svgrepo-com](https://github.com/manualdousuario/dez/assets/19216581/416dbb13-69b5-49a0-993f-d345f459f739)

**Comment by claromes** [comment]
Você tem um ponto.

Quer aproveitar essas atualizações de ícones e trocar logo o do menu?

**Comment by rghedin** [comment]
Vamos nessa. Cria um PR com a troca do ícone, por favor? Aí eu submeto um commit com o `header.php` com os menus alterados para esse enfoque em opções do usuário.
