### ISSUE TITLE
Trazer o CSS do Órbita para dentro do `style.css` do Dez?

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/dez#25]
Com a chamada dos cinco posts mais populares do Órbita na capa do **Manual**, os arquivos do Órbita são carregados em praticamente todas as páginas do site (só não nas páginas páginas e nas de arquivos).

Isso significa que a maioria das páginas, e as mais acessadas (capa e posts), estão carregando dois arquivos `*.css`: o do tema (`style.css`) e o do Órbita (`main.css`).

Penso em juntar os dois. Não sei se teria como fazer algo automatizado; de qualquer forma, não é muito trabalho copiar manualmente o `main.css` para dentro do `style.css` a cada atualização do Órbita e editar o `orbita.php` para não puxar o CSS. (Outra saída, talvez, fosse deixar as funções de enqueue do `main.css` comentadas/desativadas no plugin.)

Algum contra? Sugestões para outras abordagens?

**Comment by claromes** [comment]
Para testar localmente qualquer mudança do Órbita, será necessário ter esse tema instalado e ele deverá estar atualizado. Meu raciocínio está certo aqui?

Não acho interessante um repo depender do outro.

**Comment by rghedin** [comment]
Sim, embora já haja alguma dependência — algumas variáveis do CSS do Órbita dependem do `style.css` do Dez.

Como não tem ninguém além de nós usando, talvez seja um arranjo viável por enquanto?

**Comment by claromes** [comment]
Verdade. Mas uma coisa é importante, talvez tenha código de lá que seja repetido, com um único CSS teremos que revisar isso.

**Comment by rghedin** [comment]
É, talvez não valha o esforço. Além disso, nesse meio tempo descobri o `<link rel="preload" … >` para folhas de estilo que resolve o problema delas bloquearem o carregamento da página até serem carregadas por completo.

Vou marcar esta issus como resolvida. Bola pra frente.
