### ISSUE TITLE
Novo cabeçalho mais informativo

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/dez#43]
Estava lendo umas coisas de UX e newsletters. Abri o site do **Manual** e tentei me colocar no lugar de alguém que tenha caído ali pela primeira vez. Talvez falte um pouco de informação no topo, não?

Fiz um mockup aqui de algo que talvez sane esse problema:

<img width="940" alt="Captura de Tela 2024-02-22 às 17 28 29" src="https://github.com/manualdousuario/dez/assets/19216581/8d03cf53-6122-4bfa-9dba-ca7cbd929d15">

Aproveito o parágrafo como menu também, “polvilhando” links importantes no texto.

Ainda não estou certo se funciona, ou se é uma boa ideia.

**Comment by claromes** [comment]
Fiquei pensando: achei que nesse formato de texto corrido, ficou com cara de aviso e não de header. Eu acho legal o texto introdutório, mas senti falta de algo mais "menu". Não sei quais foram as suas referências, mas pensei em um formato sem os links no texto e organizados: 
![Captura de tela 2024-02-24 091949](https://github.com/manualdousuario/dez/assets/28742647/0f2f5834-f29c-4df2-8cb5-87cf210dc30d)

De qualquer forma, esse texto abre espaço para encaixar a busca no header. Inserir o ícone da lupa na navegação:
![Captura de tela 2024-02-24 092719](https://github.com/manualdousuario/dez/assets/28742647/6818efa7-d572-496d-953b-3352507b8657)

E quando clicado, surge o form:
![Captura de tela 2024-02-24 092853](https://github.com/manualdousuario/dez/assets/28742647/cc323d28-b28e-42cb-af79-6288d8cc0601)

O que acha?

(Talvez até tirar o BG do ícone do usuário...)

**Comment by rghedin** [comment]
Hmmm, essa solução realmente deixa as coisas mais organizadas. Tive a ideia do cabeçalho depois de topar com [este site](https://goodenough.us). Não é a mesma coisa, mas deu um estalo em mim.

Gosto do modelo inicial só por ser pouco (ou nada) convencional. Há um grande risco em tentar esse tipo de coisa (pouco ou nada convencional), principalmente de confundir os leitores, mas talvez nesse caso não aconteça?

Vamos arriscar o modelo original. Se confundir, partimos para sua proposta.

A lupa da pesquisa ali ficaria bom demais. Poderia até ser uma camada que sobrepõe todo o cabeçalho em vez de abrir embaixo dele. Eu não manjo fazer isso :(

O BG do usuário eu acho legal manter. Acho aquele menu mais importante que o ícone da aparência e um eventual ícone da pesquisa, e talvez sirva também como distinção do ícone que tem mais coisas embaixo/segundo nível.

**Comment by rghedin** [comment]
Aliás, dei uma boa enxugada no texto. Dá para ver no [staging](https://staging-ef65-rghedin.wpcomstaging.com).

**Comment by rghedin** [comment]
Uma dúvida de leigo em git, @claromes: nesse caso, eu continuo trabalhando no branch revertido (`2024-6`) ou crio um novo? Tinha algumas alterações no CSS fora do cabeçalho e rodapé naquele branch que gostaria de manter.

**Comment by claromes** [comment]
Abre um novo, aquele eu já fiz o merge. Mas se quiser posso voltar a main para o código do 2.7, só que você vai precisar escrever essas mudanças de novo.

**Comment by rghedin** [comment]
Vou abrir um novo. Valeu!

**Comment by claromes** [comment]
Continuando...

Minha sugestão de menu completo:

![Captura de tela 2024-03-31 231706](https://github.com/manualdousuario/dez/assets/28742647/e88839d0-6b2d-4a79-ad94-3dbf9536af5c)

![Captura de tela 2024-03-31 235531](https://github.com/manualdousuario/dez/assets/28742647/920ad940-60a8-4d2e-99d0-9fe175f98e6e)

Ou

![Captura de tela 2024-04-05 102612](https://github.com/manualdousuario/dez/assets/28742647/583af463-4bdf-48ef-aba2-5bebbb4a352c)

**Comment by claromes** [comment]
Entendi. Confesso que acho o ícone RSS perdido ali.

Esse espaçamento menor é proposital, certo?
![Captura de tela 2024-04-05 155538](https://github.com/manualdousuario/dez/assets/28742647/76a859f6-5e84-4f5e-b185-a674a8b0672c)

O menu hambúrguer era só uma alternativa pra deixar o header limpo em telas menores. Dado que 4 ícones (como no exemplo) + menu em texto fica muita informação.

**Comment by rghedin** [comment]
Sim, é proposital para fortalecer a relação entre newsletter e RSS. Pensando agora, talvez passe a impressão de que é um RSS da newsletter, né?

Quatro ícones e menu em texto seria muito ruim? (Seria o padrão para telas grandes, certo?) Porque estava pensando aqui, e se definirmos um `max-width: 50%;` (ou até 60%) para a classe `.site-branding` e diminuir um pouco o `gap` do bloco de ícones, cabem quatro ícones ali:

<img width="362" alt="Captura de Tela 2024-04-05 às 16 52 16" src="https://github.com/manualdousuario/dez/assets/19216581/f4a225e2-ffbc-449f-8812-cca430a1b947">

**Comment by claromes** [comment]
Acho que a diminuição na imagem já seria necessário para três ícones. Ela deve ser responsiva. Bom, vou seguir com a busca/lupa e vamos ajustando no que for necessário.

**Comment by rghedin** [comment]
A propósito, o CSS só tem um breaking point no momento (`max-width: 670px`). Talvez haja espaço para um de telas muito pequenas (`max-width: 360px`?) para empilhar os itens desse menu totalmente na vertical:

```
Logo
Menu de ícones
Menu de palavras
```

(No 3.0, tentei ao máximo evitar criar novos breaking points no CSS, mas acho que não vai ter jeito dessa vez… a menos que a gente dê um jeito usando `flex-wrap` no breaking point de 670px.)

***

Ah, meio relacionado, alguns leitores [reclamaram](https://manualdousuario.net/orbita-post/campos-de-busca-x-menu-com-itens/comment-page-1/) da ausência de seções e podcasts. Uma solução aventada ali é destacar novamente [a página de arquivo/mapa](https://manualdousuario.net/arquivo/). Gosto dessa ideia, só não sei se caberia no menu de palavras.

**Comment by claromes** [comment]
> Ah, meio relacionado, alguns leitores [reclamaram](https://manualdousuario.net/orbita-post/campos-de-busca-x-menu-com-itens/comment-page-1/) da ausência de seções e podcasts. Uma solução aventada ali é destacar novamente [a página de arquivo/mapa](https://manualdousuario.net/arquivo/). Gosto dessa ideia, só não sei se caberia no menu de palavras.

Antes estava no user menu, não? Pode resolver até a gente finalizar o header.

**Comment by rghedin** [comment]
Sim, estava como um substituto à busca. Pelo feedback, parece que a busca não substitui o mapa 🥲 

Vou refletir um pouco aqui.

**Comment by rghedin** [comment]
#52 fechou esta issue, certo? Qualquer coisa, reabrimos.
