### ISSUE TITLE
Background do texto de alguns avisos

### ISSUE THREAD

**Issue by claromes** [manualdousuario/dez#55]
Depois da última atualização alguns avisos ficaram com background cinza no texto, no tema escuro. No tema claro estão corretos.

![Captura de tela 2024-04-30 181155](https://github.com/manualdousuario/dez/assets/28742647/ab7aba66-2524-44a4-8268-60b1d37b6b35)

![Captura de tela 2024-04-30 181129](https://github.com/manualdousuario/dez/assets/28742647/39a98662-3fe8-4a40-bdf2-5046c26ce871)

![Captura de tela 2024-04-30 214617](https://github.com/manualdousuario/dez/assets/28742647/87f1d133-1ae2-4b75-8b5f-c3d3968d24ca)

**Comment by rghedin** [comment]
Não sei por que eu fiz isso, mas é só remover este atributo:

```css
div.ctx-atencao p:last-child, div.ctx-atualizacao p:last-child, div.ctx-dica p:last-child, div.ctx-editor p:last-child, div.ctx-parceiros p:last-child, div.ctx-transparencia p:last-child, div.podcast_player p:last-child {
background: var(--cor-destaques);
```

Deixa comigo!
