### ISSUE TITLE
`scroll-behavior: smooth;` parou de funcionar

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/dez#56]
Zero ideia do porquê disso, mas o `scroll-behavior: smooth;`, que está no `body`, não funciona mais.

No Safari, pelo menos, esse atributo deixava as rolagens automáticas bem suaves, em vez do salto seco. Exemplos:

* Ao clicar/tocar na setinha do canto inferior direito, para voltar ao topo da página;
* Ao clicar nos botões de comentários, que têm a âncora `#comments`.

Ideias?

**Comment by claromes** [comment]
É só tirar do body e colocar no seletor universal. Vou abrir um PR.

**Comment by rghedin** [comment]
Boa! Já revisei e aprovei.

Aproveitei o embalo para mandar outro PR que corrige um detalhe do post format `podcasts` que deixei passar na `v3.2.2`. Já tinha escrito ele, não sei se tá compatível com o seu ou se precisa de alterações. (Ainda me bato para entender algumas lógicas do git.) Avise-me, qualquer coisa, para eu adequar o meu PR a este seu, por favor.

**Comment by claromes** [comment]
Release atualizado.

Sobre o git, deu conflito, pois ajustamos os mesmo arquivos. Isso significa que estamos tentando atualizar a branch `main` de duas formas diferentes.

Como você fez a revisão, poderia ter dado merge e feito seu PR a partir da nova `main`, com as minhas alterações.
Mas tá tudo certo.

**Comment by rghedin** [comment]
Ahhh, bom saber! Ficarei atento nas próximas. Valeu, @claromes!
