### ISSUE TITLE
“Números enormes”, nova seção no site

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/dez#60]
Faz um tempão que quero implementar isso no site. Não sei como (minhas ideias/tentativas se mostraram falhas), daí pensei em abrir aqui.

A ideia é ter uma seção/leiaute, atrelado a uma tag ou categoria, para Números Enormes: um numerozão seguido de uma pequena explicação do contexto. Parecido com os posts de citações ([exemplo](https://manualdousuario.net/citacao-jeff-bezos-signal/)), só que com o número em vez da frase.

O problema é tornar o numerozão responsivo, ou seja, que fique grande em todas os tamanhos de tela, mas sem quebrar a linha.

* O numerozão pode ser a primeira linha do post. É importante manter o título descritivo e, na saída, oculto (`display: none`; mesmo esquema das notinhas/post format `aside`).
* Em telas pequenas, o numerozão ocuparia `100%` da largura da tela; nas grandes, `~50%`. 

Um mockup:

![mockup](https://github.com/manualdousuario/dez/assets/19216581/257bfaf5-bb21-4380-b4d1-afc8fdd94f3d)

**Comment by claromes** [comment]
Faça testes com `clamp()` no css.
Você pode criar uma classe chamada `ctx-number` para inserir o estilo.

Ficaria assim:
![mdu-ezgif com-resize](https://github.com/manualdousuario/dez/assets/28742647/98a79e7d-3dfd-4622-97ce-11e5305642b1)

No código:

```css
.ctx-number {
    font-size: clamp(2rem, 12vw, 5rem);
    white-space: nowrap;
}
```
```html
<span class="ctx-number">US$ 20 bilhões</span>
```
