### ISSUE TITLE
Uma reflexão sobre o header na versão mobile

### ISSUE THREAD

**Issue by claromes** [manualdousuario/dez#67]
Ocupa quase a metade da tela!

![Captura de tela 2024-06-29 173201](https://github.com/manualdousuario/dez/assets/28742647/9daf868b-4811-4afb-b73d-c8009d5ce411)

**Comment by rghedin** [comment]
Pior, né? O cabeçalho ficou meio inchado nos últimos meses e a solução mais comum (ou a que me ocorre) para esses casos é o menu de hambúrguer, o que talvez não caiba no momento.

A menos que a gente reformule o ícone do usuário para ser o menu de hambúrguer em telas pequenas. Algo assim:

![Sem Título](https://github.com/manualdousuario/dez/assets/19216581/893e31d3-c362-4520-aa01-f70c5694b4a4)

**Comment by rghedin** [comment]
Fiquei pensando nesse assunto, @claromes, e acho que cheguei numa boa solução. O mockup:

![mockup-2](https://github.com/manualdousuario/dez/assets/19216581/be4f9d86-edb3-4b7c-856d-1f6925a2ac26)

Explicando o paradeiro dos itens ausentes:

* Link da newsletter vai para a barrinha do topo e abandonamos o aviso de novos posts às sextas. Dá para colocar isso no `Sobre`, relembrar na newsletter e, com o tempo, a audiência se acostuma.
* O ícone da aparência (claro/escuro) a gente move para o rodapé. É um negócio raramente usado, então não acho que exista prejuízo em deixá-lo com pouco destaque.
* O ícone do RSS é eliminado. Os clientes de feeds conseguem detectar o feed a partir da URL do site. Pensando assim, o ícone torna-se dispensável. (Já era antes; tinha colocado ele ali mais como um reforço/“publicidade” para o RSS.)

Podemos eliminar toda a segunda parte do menu do usuário, deixando ele, de fato, um menu *do usuário*. E o mapa do **Manual** fica destacado logo no início da página `Sobre`.

A dificuldade aí seria adaptar a busca. Como não teremos dois menus, ao ativá-la o campo de texto se sobreporia ao único menu, então teria que alterar o funcionamento dele para sumir com o campo de texto com um clique/toque fora do campo de texto.

O que acha?

**Comment by claromes** [comment]
Vi o PR, mas vou seguir com a conversa por aqui... A solução ficou ótima.
Mas acho que podemos manter a configuração de aparência no topo, dentro do menu de usuário, já que isso é uma configuração de uso. Mas trocaria o ícone por texto. Ficou perdido no footer.

Minha sugestão seria manter a ordem dos menus (texto e ícones), porém alterando o menu de texto para flex-start a partir de 515px. Diminuir os ícones para 20 ou 22px e colocar o logo no centro (`.site-header` com justify-content: center;).


![Captura de tela 2024-07-03 122251](https://github.com/manualdousuario/dez/assets/28742647/2197f119-4fb9-4dd9-ab4b-c8bfab89ec03)

**Comment by rghedin** [comment]
Ótimas ideias, @claromes! Só deixei o breaking point em 529 px porque com 515 px, os ícones “caíam” para a linha de baixo quando o campo da pesquisa era ativado.

Acabei de subir as correções.
