### ISSUE TITLE
restaurar botão da aparência (claro/escuro) no cabeçalho

### ISSUE THREAD

**Issue by rghedin** [manualdousuario/dez#78]
Com a remoção do item “Newsletter” do cabeçalho na [v3.4.4](https://github.com/manualdousuario/dez/pull/77), ganhamos espaço ali para restaurar o [ícone de claro/escuro](https://github.com/manualdousuario/dez/pull/36/files/5c3b318b8d908adedd1ffa40840235dfbdc90c8d) que foi movido para o menu do usuário em algum momento.

Seria legal trazê-lo de volta. Na pesquisa de fim de ano com os leitores, alguém pediu por um botão para alternar a aparência do site, o que sinaliza que ele está escondido na implementação atual.

**Comment by claromes** [comment]
Beleza. É procurar pelo código anterior e implementar de volta.
